[package]
name = "trankeel-graphql"
version = "0.5.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = { version = "3.0.29", features = ["apollo_tracing", "log"] }
trankeel = { path = "../lib" }
serde = "1.0"
