[package]
name = "piteo-graphql"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version = "2.9.10", git = "https://github.com/async-graphql/async-graphql", features = ["apollo_tracing", "uuid"] }
piteo-core = { path = "../core" }
piteo-lib = { path = "../lib" }
serde = "1.0"
