[package]
name = "trankeel-graphql"
version = "0.6.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = { version = "3.0.28", features = ["apollo_tracing", "tracing"] }
futures-timer = "3.0.2"
trankeel = { path = "../lib" }
serde = "1.0"
