[package]
name = "trankeel-graphql"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
async-graphql = { version = "3.0.17", features = ["apollo_tracing"] }
trankeel = { path = "../lib" }
serde = "1.0"
