# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "packages/data/src/schema.rs"
import_types = ["diesel::sql_types::*;\n#[allow(unused_imports)]\nuse crate::sql_types::*"]
