[templates]
receipt_document = { id = "8269E571-7ECE-4F0D-BC37-854D77999E0D", path = "templates/receipt_document.html" }
receipt_created_mail = { id = "1", path = "templates/receipt_created_mail.html" }
candidacy_created_mail = { id = "2", path = "templates/candidacy_created_mail.html" }
candidacy_accepted_mail = { id = "3", path = "templates/candidacy_accepted_mail.html" }
candidacy_rejected_text = { id = "", path = "templates/candidacy_rejected_text.html" }

[routes]
candidacy_url = "/candidacies/:id"
invite_url = "/register?invite=:token"
