#[macro_use]
extern crate diesel;

mod database;
mod schema;

pub mod auth;
pub mod billing;
pub mod companies;
pub mod error;
pub mod files;
pub mod leases;
pub mod owners;
pub mod properties;
pub mod reports;
pub mod tenants;

pub use piteo_data::Address;
pub use piteo_data::Amount;
pub use piteo_data::AuthId;
pub use piteo_data::DateTime;
pub use piteo_data::FileStatus;
pub use piteo_data::FileType;
pub use piteo_data::Id;
pub use piteo_data::ImportSource;
pub use piteo_data::LeaseFurnishedDuration;
pub use piteo_data::LeaseNakedDuration;
pub use piteo_data::LeaseRentPeriodicity;
pub use piteo_data::LeaseRentReferenceIrl;
pub use piteo_data::LeaseStatus;
pub use piteo_data::LeaseType;
pub use piteo_data::LegalEntity;
pub use piteo_data::LegalEntityType;
pub use piteo_data::Name;
pub use piteo_data::PlanCode;
pub use piteo_data::PropertyBuildPeriodType;
pub use piteo_data::PropertyBuildingLegalStatus;
pub use piteo_data::PropertyEnergyClass;
pub use piteo_data::PropertyGasEmission;
pub use piteo_data::PropertyHabitationUsageType;
pub use piteo_data::PropertyRoomType;
pub use piteo_data::PropertyStatus;
pub use piteo_data::PropertyUsageType;
pub use piteo_data::RentChargesRecuperationMode;
pub use piteo_data::RentPaymentMethod;
pub use piteo_data::RentStatus;
pub use piteo_data::SubscriptionStatus;
pub use piteo_data::Tenant;
pub use piteo_data::TenantStatus;
pub use piteo_data::TransactionType;
pub use piteo_data::UserRole;

pub use crate::auth::Account;
pub use crate::auth::Person;
pub use crate::billing::Plan;
pub use crate::companies::Company;
pub use crate::database::build_connection_pool;
pub use crate::database::DbPool;
pub use crate::error::Error;
pub use crate::leases::Lease;
pub use crate::leases::LeaseData;
pub use crate::leases::Rent;
pub use crate::owners::Identity;
pub use crate::owners::Lender;
pub use crate::properties::Property;
pub use crate::reports::Summary;
