[package]
name = "trankeel-ops"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
async-graphql = "3.0.23"
chrono = "0.4.19"
eyre = "0.6.5"
thiserror = "1.0.30"
trankeel-data = { path = "../data" }
serde = "1.0"
serde_json = "1.0"
validator = { version = "0.14.0", features = ["derive"] }
