[package]
name = "trankeel-ops"
version = "0.5.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-graphql = "3.0.31"
chrono = "0.4.19"
eyre = "0.6.6"
thiserror = "1.0.30"
trankeel-data = { path = "../data" }
serde = "1.0"
serde_json = "1.0"
validator = { version = "0.14.0", features = ["derive"] }
