[package]
name = "trankeel-api"
version = "0.6.0"
edition = "2021"
default-run = "trankeel-api"

[features]
default = ["dotenv"]
release = ["async-stripe", "pdfmonkey", "sendinblue", "sentry"]
async-stripe = ["trankeel/async-stripe"]
pdfmonkey = ["trankeel/pdfmonkey"]
sendinblue = ["trankeel/sendinblue"]

[dependencies]
async-graphql-poem = "3.0.34"
chrono = "0.4.19"
dotenv = { version = "0.15.0", optional = true }
firebase-admin-auth-rs = "0.1.0"
log = "0.4.14"
poem = { version = "1.2.59", features = ["websocket"] }
sentry = { version = "0.24.3", optional = true }
serde = "1.0"
serde_json = "1.0"
tera = "1.15.0"
thiserror = "1.0.30"
tokio = { version = "1.10.0", features = ["full"] }
tracing-subscriber = "0.3.9"
trankeel = { path = "../lib" }
trankeel-graphql = { path = "../gql" }
