[package]
name = "trankeel-api"
version = "0.5.0"
edition = "2021"
default-run = "trankeel-api"

[features]
default = ["dotenv"]
release = ["async-stripe", "pdfmonkey", "sendinblue", "sentry"]
async-stripe = ["trankeel/async-stripe"]
pdfmonkey = ["trankeel/pdfmonkey"]
sendinblue = ["trankeel/sendinblue"]

[dependencies]
async-graphql-rocket = "3.0.31"
chrono = "0.4.19"
dotenv = { version = "0.15.0", optional = true }
firebase-admin-auth-rs = "0.1.0"
log = "0.4.14"
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master", default-features = false }
rocket_dyn_templates = { version = "0.1.0-rc.1", features = ["tera"] }
sentry = { version = "0.24.2", optional = true }
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.10.0", features = ["full"] }
tracing-subscriber = "0.3.9"
trankeel = { path = "../lib" }
trankeel-graphql = { path = "../gql" }
