[package]
name = "trankeel-api"
version = "0.3.0"
edition = "2018"
default-run = "trankeel-api"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql-rocket = "2.11.3"
dotenv = "0.15.0"
jsonwebtoken = "7.2.0"
trankeel = { path = "../lib" }
trankeel-graphql = { path = "../gql" }
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", branch = "master", default-features = false }
sentry = "0.23.0"
serde = "1.0"
