[package]
name = "piteo-api"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version = "2.9.10", git = "https://github.com/async-graphql/async-graphql" }
async-graphql-rocket = { version = "2.0.8", git = "https://github.com/async-graphql/async-graphql" }
dotenv = "0.15.0"
piteo-core = { path = "../core" }
rocket = { version = "0.5.0-rc.1", default-features = false }
