[alias]
dev = "watch --clear --exec=run --ignore=schema.graphql"
lint = "clippy"
coverage = "llvm-cov"
codegen = "run --bin=trankeel-cli -- codegen"
migrate = "run --bin=trankeel-cli -- migrate"
seed = "run --bin=trankeel-cli -- seed"
