[alias]
dev = "watch --clear --exec=run --ignore=schema.graphql"
lint = "clippy"
coverage = "llvm-cov"
generate = "run --bin=trankeel-cli -- generate"
migrate = "run --bin=trankeel-cli -- migrate"
seed = "run --bin=trankeel-cli -- seed"

[build]
target-dir = "build"
