[package]
name = "piteo-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piteo-data = { path = "../data" }
diesel = { version = "1.4.7", features = ["postgres", "r2d2", "uuidv07", "serde_json", "chrono", "numeric"] }
eyre = "0.6.5"
serde = "1.0"
serde_json = "1.0"
validator = { version = "0.14.0", features = ["derive"] }
