[package]
name = "piteo-core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-graphql = { version = "2.9.10", git = "https://github.com/async-graphql/async-graphql", features = ["uuid"] }
async-trait = "0.1.51"
diesel = { version = "1.4.7", features = ["postgres", "r2d2", "uuidv07", "serde_json", "chrono", "numeric"] }
eyre = "0.6.5"
log = "0.4.14"
piteo-data = { path = "../data" }
serde = "1.0"
serde_json = "1.0"
validator = { version = "0.14.0", features = ["derive"] }
