[package]
name = "trankeel-core"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
async-stripe = { version = "0.13.0-rc3", default-features = false, features = ["runtime-tokio-hyper", "billing"] }
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "uuidv07", "serde_json", "chrono", "numeric"] }
erased-serde = "0.3"
eyre = "0.6.5"
futures = { version = "0.3.19", default-features = false }
liquid = "0.23.1"
log = "0.4.14"
pdfmonkey = { path = "../ext/pdfmonkey", optional = true }
reqwest = { version = "0.11.8", features = ["json"] }
sendinblue = { version = "0.2.1", optional = true }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0.30"
tokio = { version = "0.2", features = ["rt-core"] }
trankeel-data = { path = "../data" }
trankeel-kit = { path = "../kit" }
trankeel-ops = { path = "../ops" }
