[package]
name = "trankeel-core"
version = "0.6.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
async-stripe = { version = "0.13.0", default-features = false, features = ["runtime-tokio-hyper", "billing", "checkout"], optional = true }
async-trait = "0.1.52"
chrono = { version = "0.4.19", features = ["serde"] }
diesel = { version = "1.4.8", features = ["postgres", "r2d2", "uuidv07", "serde_json", "chrono", "numeric"] }
erased-serde = "0.3"
eyre = "0.6.6"
futures = { version = "0.3.21", default-features = false }
liquid = "0.23.1"
log = "0.4.14"
pdfmonkey = { path = "../ext/pdfmonkey", optional = true }
remain = "0.2.2"
reqwest = { version = "0.11.9", features = ["json"] }
sendinblue = { version = "0.2.1", optional = true }
serde = "1.0"
serde_json = "1.0"
sqlx = { version = "0.5.11", features = [ "postgres", "tls", "runtime-tokio-native-tls" ] }
thiserror = "1.0.30"
tokio = { version = "0.2", features = ["rt-core"] }
trankeel-data = { path = "../data" }
trankeel-kit = { path = "../kit" }
trankeel-ops = { path = "../ops" }
