[package]
name = "trankeel-kit"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.19" }
colored_json = "2.1.0"
figment = { version = "0.10.6", features = ["toml"] }
regex = "1.5.4"
serde = "1.0"
serde_json = "1.0"
toml = "0.5.8"
