[package]
name = "trankeel-kit"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[dependencies]
chrono = { version = "0.4.19", default-features = false }
serde = "1.0"
toml = "0.5.8"
