[package]
name = "trankeel-kit"
version = "0.5.0"
edition = "2021"

[lib]
doctest = false

[dependencies]
chrono = { version = "0.4.19" }
colored_json = "2.1.0"
figment = { version = "0.10.6", features = ["env", "toml"] }
regex = "1.5.4"
serde = "1.0"
serde_json = "1.0"
toml = "0.5.8"
