[package]
name = "trankeel-cli"
version = "0.3.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "trankeel-cli"
path = "src/cli.rs"

[dependencies]
chrono = "0.4.19"
dotenv = "0.15.0"
trankeel = { path = "../lib" }
trankeel-graphql = { path = "../gql" }
regex = "1.5.4"
tokio = { version = "1.10.0", features = ["full"] }
