[package]
name = "trankeel-cli"
version = "0.6.0"
edition = "2021"

[[bin]]
name = "trankeel-cli"
path = "src/cli.rs"

[features]
default = ["dotenv"]

[dependencies]
chrono = "0.4.19"
dotenv = { version = "0.15.0", optional = true }
log = "0.4.14"
tokio = { version = "1.10.0", features = ["full"] }
tracing-subscriber = "0.3.9"
trankeel = { path = "../lib" }
trankeel-graphql = { path = "../gql" }
