name: cd

on:
  push:
    branches: [main]
    tags: [v*]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/setup-buildx-action@v1

      # https://devcenter.heroku.com/articles/container-registry-and-runtime#logging-in-to-the-registry
      - uses: docker/login-action@v1
        with:
          registry: registry.heroku.com
          username: _
          password: ${{ secrets.HEROKU_API_KEY }}

      # https://devcenter.heroku.com/articles/container-registry-and-runtime#build-an-image-and-push
      - uses: docker/build-push-action@v2
        with:
          load: true
          tags: registry.heroku.com/piteo-rs/web

      # https://devcenter.heroku.com/articles/container-registry-and-runtime#pushing-an-existing-image
      - run: docker push registry.heroku.com/piteo-rs/web

      # https://devcenter.heroku.com/articles/container-registry-and-runtime#releasing-an-image
      - run: heroku container:release web --app piteo-rs
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
