name: ci

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy

      - uses: swatinem/rust-cache@v1

      - run: cargo build --release --locked

      - run: cargo clippy --release --locked -- --deny warnings

      - run: cargo test --release --locked
