name: ci

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          components: rustfmt, clippy

      - uses: swatinem/rust-cache@v1

      - run: cargo fmt --check

      - run: cargo build --release --locked --all-features

      - run: cargo clippy --release --locked --all-features -- --deny warnings

      - run: cargo test --release --locked --all-features
